package com.example.crud.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "employees")
public class Employee {
    @DynamoDBHashKey(attributeName = "employeeId")
    @DynamoDBAutoGeneratedKey
    private String employeeId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private int pay;
    @DynamoDBAttribute
    private String location;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String position;
    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private Admin admin;

}
